name: avex_mobile
description: A new Flutter project
publish_to: "none" 

version: 0.3.0+1

environment:
  sdk: ">3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bip32: ^2.0.0
  bip39: ^1.0.6
  blur: ^3.1.0
  bs58: ^1.0.2
  cached_network_image: ^3.2.3
  chart_sparkline: ^1.0.13
  connectivity_plus: ^5.0.0
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  dots_indicator: ^3.0.0
  dropbox_client: ^1.0.0
  eddsa_hmac:
    path: ../eddsa_hmac_dart
  envied: ^0.3.0+3
  eth_sig_util: ^0.0.9
  firebase_core: ^2.4.1
  firebase_dynamic_links: ^5.0.11
  file: ^6.1.4
  file_picker: ^5.2.6
  flutter_animate: ^4.2.0+1
  flutter_gravatar: ^2.0.2
  flutter_inappwebview: ^5.7.2+3
  flutter_injected_web3: ^1.0.1
  flutter_phoenix: ^1.1.1
  flutter_riverpod: ^2.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  go_router: ^11.1.2
  google_fonts: ^4.0.3
  google_sign_in: any
  googleapis: any
  http: ^0.13.5
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: any
  kadena_dart_sdk: ^2.3.0
  lottie: ^2.3.2
  logger: ^2.0.2+1
  marquee: ^2.2.3
  mccounting_text: ^1.0.0
  mobile_scanner: ^3.2.0
  open_mail_app: ^0.4.5
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  pretty_qr_code: ^3.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: any
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  video_player: ^2.7.0
  walletconnect_flutter_v2: ^2.0.8

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  go_router_builder: ^2.3.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.5.4
  retrofit_generator: any

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
    lottie: true
    
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

